# Generated by Django 5.1 on 2024-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
