# Generated by Django 4.2.15 on 2024-08-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_profile_facebook_profile_homepage_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(default='Post title', max_length=50),
        ),
    ]
