# Generated by Django 4.2.15 on 2024-08-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
